export default {
  name: "HiVPN",
  networks: {
    "56": {
      id: 56,
      name: "BNB Smart Chain",
      address: "0x791e539089691D44cC0d1567505a2e6492F94859",
      network: "bsc",
      nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
      rpcUrls: {
        default: "https://bsc-dataseed.binance.org",
        public: "https://bsc-dataseed.binance.org",
      },
      blockExplorers: {
        etherscan: {
          name: "Etherscan",
          url: "https://bscscan.com/",
        },
        default: {
          name: "Etherscan",
          url: "https://bscscan.com/",
        },
      },
      testnet: false,
    },
    "97": {
      id: 97,
      name: "BNB Smart Chain Testnet",
      address: "0x791e539089691D44cC0d1567505a2e6492F94859",
      network: "bsc-testnet",
      nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
      rpcUrls: {
        default: "https://data-seed-prebsc-1-s1.binance.org:8545",
        public: "https://data-seed-prebsc-1-s1.binance.org:8545",
      },
      blockExplorers: {
        etherscan: {
          name: "Etherscan",
          url: "https://testnet.bscscan.com/",
        },
        default: {
          name: "Etherscan",
          url: "https://testnet.bscscan.com/",
        },
      },
      testnet: true,
    },
  },
  abi: [
    { inputs: [], stateMutability: "nonpayable", type: "constructor" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "user",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "referrer",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "value",
          type: "uint256",
        },
      ],
      name: "BuyVpn",
      type: "event",
    },
    {
      inputs: [],
      name: "BNBPrice",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "BNBValue",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "BNBtoUSD",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "PLAN",
      outputs: [{ internalType: "uint40", name: "", type: "uint40" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "referrer", type: "address" },
        { internalType: "uint256", name: "plan", type: "uint256" },
      ],
      name: "Pay",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "TIME",
      outputs: [{ internalType: "uint40", name: "", type: "uint40" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "TOLERANCE_DOWN",
      outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "TOLERANCE_UP",
      outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "USDtoBNB",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "changeOwner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint8", name: "index", type: "uint8" },
        { internalType: "uint40", name: "plan", type: "uint40" },
      ],
      name: "changePrice",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint8", name: "index", type: "uint8" },
        { internalType: "uint40", name: "time", type: "uint40" },
      ],
      name: "changeTime",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint128", name: "tolerance", type: "uint128" }],
      name: "changeToleranceDown",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint128", name: "tolerance", type: "uint128" }],
      name: "changeToleranceUp",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "uint256", name: "index", type: "uint256" },
        {
          components: [
            { internalType: "uint64", name: "time", type: "uint64" },
            { internalType: "uint64", name: "amount", type: "uint64" },
            { internalType: "uint64", name: "duration", type: "uint64" },
            { internalType: "uint64", name: "bnbAmount", type: "uint64" },
          ],
          internalType: "struct IHiVpn.BuyDetail",
          name: "detail",
          type: "tuple",
        },
      ],
      name: "changeUserBuy",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "findPlan",
      outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "resetUser",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "userBuyDetails",
      outputs: [
        {
          components: [
            { internalType: "uint64", name: "time", type: "uint64" },
            { internalType: "uint64", name: "amount", type: "uint64" },
            { internalType: "uint64", name: "duration", type: "uint64" },
            { internalType: "uint64", name: "bnbAmount", type: "uint64" },
          ],
          internalType: "struct IHiVpn.BuyDetail[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "userDepositNumber",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "userTotalBuys",
      outputs: [
        { internalType: "uint256", name: "totalAmount", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "users",
      outputs: [
        { internalType: "uint64", name: "time", type: "uint64" },
        { internalType: "uint64", name: "amount", type: "uint64" },
        { internalType: "uint64", name: "duration", type: "uint64" },
        { internalType: "uint64", name: "bnbAmount", type: "uint64" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "withdrawBnb",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    { stateMutability: "payable", type: "receive" },
  ],
} as const
